import { Button } from '@/components/ui/Button';
import { useAuthenticatedFetch } from '@/lib/hooks/use-authenticated-fetch';
import React from 'react';
import toast from 'react-hot-toast';
import { useTranslation } from 'react-i18next';

type UsbDevice = {
  device: string;
  model?: string | null;
  size?: string | null;
  mountpoint?: string | null;
  uuid?: string | null;
  label?: string | null;
};

type InstalledApps = {
  nextcloud: boolean;
  jellyfin: boolean;
  immich: boolean;
};

export default function ExternalUsbPage() {
  const { t } = useTranslation();
  const authenticatedFetch = useAuthenticatedFetch();

  const [loading, setLoading] = React.useState(false);
  const [error, setError] = React.useState('');
  const [devices, setDevices] = React.useState<UsbDevice[]>([]);
  const [busyDevice, setBusyDevice] = React.useState<string | null>(null);
  const [installedApps, setInstalledApps] = React.useState<InstalledApps | null>(null);

  // New selection state: only one USB device and one app can be selected at a time.
  const [selectedDevice, setSelectedDevice] = React.useState<string | null>(null);
  const [selectedApp, setSelectedApp] = React.useState<string>('');
  const [isMounted, setIsMounted] = React.useState<boolean>(false);
  const [selectingDevice, setSelectingDevice] = React.useState<string | null>(null);
  const [savingApp, setSavingApp] = React.useState<boolean>(false);

  // Keep track of latest selection state for cleanup on unmount.
  const latestSelectionRef = React.useRef({ selectedDevice: null as string | null, selectedApp: '' as string, isMounted: false });
  React.useEffect(() => {
    latestSelectionRef.current = { selectedDevice, selectedApp, isMounted };
  }, [selectedDevice, selectedApp, isMounted]);

  // Load last selected device/app/mounted state from backend so the UI
  // reflects any previous selection without requiring a new scan.
  React.useEffect(() => {
    const loadSelection = async () => {
      try {
        const res = await authenticatedFetch('/api/config/usb/selected');
        if (!res.ok) return;
        const data = await res.json();
        const dev = typeof data?.device === 'string' && data.device ? data.device : null;
        const app = typeof data?.app === 'string' && data.app ? data.app : '';
        const mounted = Boolean(data?.mounted);
        if (dev) {
          setSelectedDevice(dev);
          if (app) setSelectedApp(app);
          setIsMounted(mounted);

          // Auto-scan to populate device list so cards are visible when
          // revisiting the page after a successful mount.
          try {
            const scanRes = await authenticatedFetch('/api/config/usb/scan', { method: 'POST' });
            const scanData = await scanRes.json();
            if (!scanRes.ok || scanData?.error) return;
            const list = Array.isArray(scanData?.devices) ? scanData.devices : [];
            setDevices(list);
          } catch {
            // ignore scan errors; user can still manually rescan
          }
        } else {
          setIsMounted(false);
        }
      } catch {
        // ignore errors, selection is best-effort
      }
    };

    // Fetch installed apps
    const fetchInstalledApps = async () => {
      try {
        const res = await authenticatedFetch('/api/config/usb/installed-apps');
        if (!res.ok) return;
        const data = await res.json();
        setInstalledApps(data);
      } catch {
        // ignore errors
      }
    };

    void loadSelection();
    void fetchInstalledApps();
  }, [authenticatedFetch]);

  // When leaving the External USB page with a pending (unmounted)
  // selection, clear the backend selection so the page starts fresh
  // next time.
  React.useEffect(() => {
    return () => {
      const { selectedDevice: dev, selectedApp: app, isMounted: mounted } = latestSelectionRef.current;
      if (!mounted && (dev || app)) {
        void authenticatedFetch('/api/config/usb/clear-selected', { method: 'POST' }).catch(() => {});
      }
    };
  }, [authenticatedFetch]);

  const refreshList = async () => {
    // usb_list.json is generated by the scan script; to reflect mountpoint changes, re-run scan.
    const res = await authenticatedFetch('/api/config/usb/scan', { method: 'POST' });
    const data = await res.json();
    if (!res.ok) throw new Error(data?.message || `Request failed: ${res.status}`);
    if (data?.error) throw new Error(String(data.error));
    const list: UsbDevice[] = Array.isArray(data?.devices) ? data.devices : [];
    setDevices(list);
    if (selectedDevice) {
      const matched = list.find((d: UsbDevice) => d.device === selectedDevice);
      setIsMounted(Boolean(matched?.mountpoint));
    } else {
      setIsMounted(false);
    }
  };

  const onScan = async () => {
    setLoading(true);
    setError('');
    try {
      const res = await authenticatedFetch('/api/config/usb/scan', { method: 'POST' });
      const data = await res.json();
      if (!res.ok) throw new Error(data?.message || `Request failed: ${res.status}`);
      if (data?.error) throw new Error(String(data.error));
      const list: UsbDevice[] = Array.isArray(data?.devices) ? data.devices : [];
      setDevices(list);
      if (selectedDevice) {
        const matched = list.find((d: UsbDevice) => d.device === selectedDevice);
        setIsMounted(Boolean(matched?.mountpoint));
      } else {
        setIsMounted(false);
      }
      toast.success('USB devices scanned');
    } catch (e: any) {
      const msg = String(e);
      setError(msg);
      toast.error(msg);
    } finally {
      setLoading(false);
    }
  };

  const onMount = async () => {
    if (!selectedDevice) return;
    setBusyDevice(selectedDevice);
    setError('');
    try {
      const res = await authenticatedFetch('/api/config/usb/mount', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ device: selectedDevice }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data?.message || `Request failed: ${res.status}`);
      if (data?.error) throw new Error(String(data.error));
      await refreshList();
      toast.success('Device mounted successfully');
    } catch (e: any) {
      const msg = String(e);
      setError(msg);
      toast.error(msg);
    } finally {
      setBusyDevice(null);
    }
  };

  const onUnmount = async () => {
    if (!selectedDevice) return;
    setBusyDevice(selectedDevice);
    setError('');
    try {
      const res = await authenticatedFetch('/api/config/usb/unmount', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ device: selectedDevice }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data?.message || `Request failed: ${res.status}`);
      if (data?.error) throw new Error(String(data.error));
      await refreshList();
      // Reset the app selection after successful unmount
      setSelectedApp('');
      toast.success('Device unmounted successfully');
    } catch (e: any) {
      const msg = String(e);
      setError(msg);
      toast.error(msg);
    } finally {
      setBusyDevice(null);
    }
  };

  const toggleSelectDevice = async (device: string) => {
    if (isMounted) return; // When mounted, selection cannot be changed.
    setSelectingDevice(device);
    setError('');
    try {
      if (selectedDevice === device) {
        const res = await authenticatedFetch('/api/config/usb/clear-selected', { method: 'POST' });
        const data = await res.json();
        if (!res.ok || data?.ok !== true) throw new Error(data?.message || `Request failed: ${res.status}`);
        setSelectedDevice(null);
        setIsMounted(false);
        toast.success(t('EXTERNAL_USB_SELECTION_CLEARED'));
      } else {
        const res = await authenticatedFetch('/api/config/usb/select', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ device }),
        });
        const data = await res.json();
        if (!res.ok || data?.ok !== true) throw new Error(data?.message || `Request failed: ${res.status}`);
        setSelectedDevice(device);
        const matched = devices.find((d) => d.device === device);
        setIsMounted(Boolean(matched?.mountpoint));
        toast.success(t('EXTERNAL_USB_SELECTION_SAVED'));
      }
    } catch (e: any) {
      const msg = String(e);
      setError(msg);
      toast.error(msg);
    } finally {
      setSelectingDevice(null);
    }
  };

  const onSelectApp = async (app: string) => {
    if (isMounted) return; // app cannot be changed while mounted.
    setSavingApp(true);
    setError('');
    try {
      const res = await authenticatedFetch('/api/config/usb/app', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ app }),
      });
      const data = await res.json();
      if (!res.ok || data?.ok !== true) throw new Error(data?.message || `Request failed: ${res.status}`);
      setSelectedApp(app);
      toast.success(t('EXTERNAL_USB_APP_SAVED'));
    } catch (e: any) {
      const msg = String(e);
      setError(msg);
      toast.error(msg);
    } finally {
      setSavingApp(false);
    }
  };

  return (
    <div className="card p-3">
      <h3 className="mb-3">{t('EXTERNAL_USB_TITLE')}</h3>

      {error && (
        <div className="alert alert-danger" role="alert">
          {error}
        </div>
      )}

      <div className="d-flex gap-2 align-items-center mb-3">
        <Button intent="primary" onClick={onScan} disabled={loading}>
          {t('EXTERNAL_USB_SCAN_BUTTON')}
        </Button>
        {loading && <div>Reading data...</div>}
      </div>

      {devices.length === 0 ? (
        <div className="text-muted">{t('EXTERNAL_USB_NO_DEVICES')}</div>
      ) : (
        <>
          <div className="d-flex flex-column gap-1 mb-3">
            <div className="d-flex px-2 py-1 fw-semibold" style={{ backgroundColor: 'var(--bs-secondary-bg)' }}>
              <div className="flex-grow-1">{t('EXTERNAL_USB_COL_NAME')}</div>
              <div style={{ width: '10rem' }}>{t('EXTERNAL_USB_COL_SIZE')}</div>
              <div style={{ width: '14rem' }}>{t('EXTERNAL_USB_COL_MODEL')}</div>
              <div style={{ width: '14rem' }}>{t('EXTERNAL_USB_COL_MOUNTPOINT')}</div>
              <div style={{ width: '12rem' }}>{t('EXTERNAL_USB_COL_ACTIONS')}</div>
            </div>

            {devices.map((d) => {
              const name = (d.label || d.device || '').toString();
              const mounted = Boolean(d.mountpoint);
              const isBusy = busyDevice === d.device || selectingDevice === d.device;
              const isSelected = selectedDevice === d.device;

              return (
                <div key={d.device} className="d-flex align-items-center px-2 py-1 border-bottom" style={{ gap: '0.5rem' }}>
                  <div className="flex-grow-1 font-monospace" style={{ wordBreak: 'break-all' }}>{name}</div>
                  <div style={{ width: '10rem' }}>{d.size || '-'}</div>
                  <div style={{ width: '14rem' }}>{d.model || '-'}</div>
                  <div className="font-monospace" style={{ width: '14rem', wordBreak: 'break-all' }}>{d.mountpoint || '-'}</div>
                  <div style={{ width: '12rem' }} className="d-flex gap-2">
                    <Button
                      intent={isSelected ? 'warning' : 'primary'}
                      disabled={isMounted || isBusy}
                      onClick={() => toggleSelectDevice(d.device)}
                    >
                      {isBusy
                        ? t('EXTERNAL_USB_WORKING')
                        : isSelected
                          ? t('EXTERNAL_USB_UNSELECT_BUTTON')
                          : t('EXTERNAL_USB_SELECT_BUTTON')}
                    </Button>
                  </div>
                </div>
              );
            })}
          </div>

          {/* App selection appears only after a device is selected */}
          {selectedDevice && (
            <div className="card mb-3 p-3" style={{ backgroundColor: 'var(--bs-secondary-bg)' }}>
              {installedApps && !installedApps.nextcloud && !installedApps.jellyfin && !installedApps.immich ? (
                <div className="alert alert-info" role="alert">
                  {t('EXTERNAL_USB_NO_APPS_INSTALLED') || 'Please install Nextcloud, Jellyfin, or Immich to mount a USB device.'}
                </div>
              ) : (
                <div className="row g-2 align-items-end">
                  <div className="col-md-4">
                    <label className="form-label">{t('EXTERNAL_USB_CHOOSE_APP_LABEL')}</label>
                    <select
                      className="form-select"
                      disabled={savingApp || isMounted}
                      value={selectedApp}
                      onChange={(e) => onSelectApp(e.target.value)}
                    >
                      <option value="">{t('EXTERNAL_USB_CHOOSE_APP_PLACEHOLDER')}</option>
                      {installedApps?.nextcloud && <option value="nextcloud">Nextcloud</option>}
                      {installedApps?.jellyfin && <option value="jellyfin">Jellyfin</option>}
                      {installedApps?.immich && <option value="immich">Immich</option>}
                    </select>
                  </div>
                  {savingApp && (
                    <div className="col-md-4 d-flex align-items-center">{t('EXTERNAL_USB_SAVING_APP')}</div>
                  )}
                </div>
              )}
            </div>
          )}

        </>
      )}

      {/* Mount / Unmount controls appear only after device and app are selected.
          This is rendered outside of the devices list so that an already-selected
          and mounted device can be unmounted even if the device list is empty
          (no rescan required). */}
      {selectedDevice && selectedApp && (
        <div className="d-flex flex-column gap-1 mt-2">
          <div className="d-flex gap-2">
            <Button
              intent="primary"
              disabled={isMounted || busyDevice !== null}
              onClick={onMount}
            >
              {busyDevice ? t('EXTERNAL_USB_WORKING') : t('EXTERNAL_USB_MOUNT_BUTTON')}
            </Button>
            <Button
              intent="warning"
              disabled={!isMounted || busyDevice !== null}
              onClick={onUnmount}
            >
              {t('EXTERNAL_USB_UNMOUNT_BUTTON')}
            </Button>
          </div>
          {busyDevice && (
            <div className="text-muted small">
              {t('EXTERNAL_USB_MOUNTING_HINT')}
            </div>
          )}
        </div>
      )}
    </div>
  );
}
